### ISSUE TITLE
Arel 6.0.0 breaks test_after_commit 0.4.0

### ISSUE THREAD

**Issue by spovich** [grosser/test_after_commit#34]
Running rails 4.2 beta4 with arel 6.0.0.beta2 and my tests are all green.  Ran a bundle update and arel 6.0.0 (just released) was installed, but my test suite is now on fire anytime factory girl tries to create a record.  Here is an example of one of the failures:

```
ArgumentError: wrong number of arguments (1 for 0)
    test_after_commit (0.4.0) lib/test_after_commit.rb:15:in `block in transaction_with_transactional_fixtures'
    test_after_commit (0.4.0) lib/test_after_commit.rb:9:in `transaction_with_transactional_fixtures'
    test/factories/users.rb:5:in `block (3 levels) in <top (required)>'
    test/models/user_test.rb:4:in `block (2 levels) in <top (required)>'
    test/models/user_test.rb:48:in `block (3 levels) in <top (required)>'
```

Reverting to arel 6.0.0.beta2 and everything is green again.

**Comment by kylefritz** [comment]
hey @spovich i'm seeing this issue in 4.2 (release w/ Arel 6.0). Did you upgrade to Rails 4.2? Are you seeing this issue?

**Comment by spovich** [comment]
@kylefritz I am on 4.2 with arel 6.0 and no longer have a problem.  Maybe double check your Gemfile/gemfile.lock?
