### ISSUE TITLE
No longer need after latest rails commit

### ISSUE THREAD

**Issue by dmitry** [grosser/test_after_commit#35]
More information is here: https://github.com/rails/rails/commit/b477ad54e586326b33528c4d68930e2efa73c72b

**Comment by grosser** [comment]
thanks!

will this be in 4.2 or 5.0 ?

**Comment by dmitry** [comment]
Looks like it will be only in 5.0 and not backported to 4.2, but anyway it's good to know that in future versions of rails there are no need to do any special rituals for marking the `after_commit` workable.

**Comment by grosser** [comment]
yep, added deprecation notice to readme

**Comment by dmitry** [comment]
Additional reference to PR: https://github.com/rails/rails/pull/18458

**Comment by pepesenaris** [comment]
I just upgrade to rails 4.2 and none of my test are working. All are falling with the same line
TypeError: no implicit conversion of nil into String
    test_after_commit (0.4.1) lib/test_after_commit.rb:15:in `block in transaction_with_transactional_fixtures'
    test_after_commit (0.4.1) lib/test_after_commit.rb:9:in `transaction_with_transactional_fixtures'

I pretty sure that it's the because of this issue.... What can do i do, other that using rails master?

**Comment by grosser** [comment]
idk works fine on my rails 4.2 app maybe because it's still on 0.2.2 :D 
patch or failed test welcome!

**Comment by pepesenaris** [comment]
You mean version 0.2.2 of test_after_commit gem?
I'll try it right away

**Comment by grosser** [comment]
yep, did not update it by accident ... might work for whatever stupid
reason ...

**Comment by grosser** [comment]
Damn ... nope just updated it in another branch and works fine on 0.4.1 ...
so yeah no idea ...

**Comment by pepesenaris** [comment]
well, no.... still does not work. it does not seems to be related to the test_after_commit version
