### ISSUE TITLE
Incorrectly called on touch?

### ISSUE THREAD

**Issue by aceofspades** [grosser/test_after_commit#37]
I have separate callbacks for `after_commit` and `after_touch` on my model. When using this gem, and I touch a model that has `belongs_to :other, touch: true`, it triggers both callbacks. I don't believe `after_commit` should be called in that case...

**Comment by grosser** [comment]
see if it gets called in non-test mode, if yes then it should be called here
afaik touch is a save -> commit ... so it would make sense ... but not sure
