### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by chamnap** [grosser/test_after_commit#43]
As rails 5 will come out soon, does this gem support rails 5 yet?

**Comment by grosser** [comment]
<img width="801" alt="screen shot 2016-05-06 at 7 58 14 am" src="https://cloud.githubusercontent.com/assets/11367/15076805/506f84d8-1360-11e6-9fd7-faeb92a12d64.png">

**Comment by chamnap** [comment]
:+1:. Sorry that i didn't see it on README. I was trying to search issues and pull requests. :)
