### ISSUE TITLE
Rails 5 Migration advice

### ISSUE THREAD

**Issue by dcosson** [grosser/test_after_commit#47]
test_after_commit is deprecated in Rails 5, but I can't find any resources on replacements for all the features.

In general after_commit hooks work out of the box now, but I'm migrating an app that sometimes turns off after_commit hooks with a block like: `TestAfterCommit.with_commits(false) { ... } `. What's the equivalent in Rails 5?

I realize that base rails features are outside the scope of this gem, but since you've decided to deprecate the gem it would be super helpful if the readme included a bit of device on migrating away from it for all the users who will inevitably hit this issue.

**Comment by grosser** [comment]
3 options afaik:
 - add stubs for these calls ... `User.any_instance.expects(:foo_hook)`
 - 
```
klass = User.class.connection.transaction_manager.current_transaction.class
klass.any_instance.stubs(:joinable?).returns false`
```
to avoid https://github.com/rails/rails/pull/18458/files
 - remove it and fix all the tests :trollface:
