### ISSUE TITLE
Not working when there is `on: :update` with `if: :some_function`

### ISSUE THREAD

**Issue by salmanasiddiqui** [grosser/test_after_commit#48]
I have been using this in my project. It works fine for other after_commit callbacks but the new one which I have added isnt working.

Following is the code from my model:
```
after_commit :do_something, on: [:update], if: :any_role_changed?

def any_role_changed?
    if previous_changes.present?
      if previous_changes[:abc].present?
        previous_changes[:abc][0] != previous_changes[:abc][1]
      elsif previous_changes[:xyz].present?
        previous_changes[:xyz][0] != previous_changes[:xyz][1]
      else
        false
      end
    else
      false
    end
  end

  def do_something
    puts 'it executed'
  end
```

Test is as follows:
```
my_model = FactoryGirl.create(:my_model, abc: false)
TestAfterCommit.with_commits(true) do
  my_model.update(abc: true)
end
```

`do_something` is never executed

Rails 4.2.8
Ruby 2.1.9
test_after_commit (1.1.0)

**Comment by grosser** [comment]
no idea ... PR welcome if you figure it out ... ideally upgrade to rails 5 and stop using this gem :D

**Comment by salmanasiddiqui** [comment]
I found the issue.
In the above code, when `  my_model.update(abc: true)` is executed, the `after_commit on: :create` callback is invoked.
If I move the creation of object inside `TestAfterCommit.with_commits(true)` then everything works as expected.
