### ISSUE TITLE
Callbacks are run inside transaction

### ISSUE THREAD

**Issue by printercu** [grosser/test_after_commit#49]
Hi!

It looks like test_after_commit runs callbacks inside transaction they invoked by, while ActiveRecord first closes transaction and then calls callbacks. I've added test:
```ruby 
# in Car
  after_commit :save_open_transactions_count
  attr_reader :open_transactions
  def save_open_transactions_count
    @open_transactions = ActiveRecord::Base.connection.open_transactions
  end

# in spec
  it "runs callback outside of transaction" do
    car = Car.create
    car.open_transactions.should == ActiveRecord::Base.connection.open_transactions
  end
```

It fails with `expected: 3,  got: 4`.

**Comment by grosser** [comment]
nice, any idea how to fix it ?
... I'm not using it anymore :(

**Comment by printercu** [comment]
I haven't seen source yet. Will try to figure out.
